# Generated by Django 4.2.7 on 2023-11-08 19:02

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_recycleuser_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=django_jalali.db.models.jDateTimeField(blank=True, default=datetime.datetime(2023, 11, 8, 19, 2, 19, 555970, tzinfo=datetime.timezone.utc), null=True, verbose_name='date joined'),
        ),
    ]
