# Generated by Django 4.2.7 on 2023-11-09 22:09

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=django_jalali.db.models.jDateTimeField(blank=True, default=datetime.datetime(2023, 11, 9, 22, 9, 25, 400241, tzinfo=datetime.timezone.utc), null=True, verbose_name='date joined'),
        ),
    ]
