# Generated by Django 4.2.7 on 2023-11-09 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0002_categorymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryModel',
        ),
    ]
